### ISSUE TITLE
Add reconnect action

### ISSUE THREAD

**Issue by cbaggers** [neil-lindquist/SLIMA#10]
**Feature-Request/Enahancement:**

This would help carry on working when SLIMA crashes but the lisp session is fine.

**Comment by neil-lindquist** [comment]
The `slime:connect` command that does this (as I mentioned on reddit).  I've added it to the SLIMA menu, and I've been trying to figure out if that makes it easy enough to find or if it should be further documented.  Do you have any thoughts on if more documentation is needed, or even a `slime:reconnect` alias?
