### ISSUE TITLE
Repl hangs.

### ISSUE THREAD

**Issue by Sokolov57** [neil-lindquist/SLIMA#11]
So I just wrote a function foo (kind of a long one), which accepts a string.
Whenever I type in the repl (foo ", it just hangs and hangs whole atom to the point I have to force close it.  Emacs is okay with it.

I can give whole source file if needed)

**Comment by neil-lindquist** [comment]
There was an infinite loop on certain incomplete expressions.  I'll push it in a new release right now, since this seems to happen anytime there's unmatched quotes.
