### ISSUE TITLE
REPL memory

### ISSUE THREAD

**Issue by thrashdin** [neil-lindquist/SLIMA#16]
A small but nice improvement. 
Emacs remembers REPL inputs from previous session -- in fact, a ton of inputs. 
Even a dirty workaround, like having a file with inputs somewhere would be very handy.
(maybe this is the only way, I don't know)

**Comment by neil-lindquist** [comment]
Slime in Emacs saves history in `~/.slime-history.eld` as the list of REPL entries as a sexp.  Do you think it would be useful to use the same history file as Emacs, or would a separate history be fine?

**Comment by thrashdin** [comment]
That is...a really nice question)
What do you think?
I kind of like the idea of shared history... because I often switch to Emacs when something seems broken in atom, thus I go there to try and replicate the problem..
To make that sort of thing decided, we'll need an actual user feedback)

**Comment by neil-lindquist** [comment]
If you'd find it useful, I might as well take that approach since it shouldn't be that much harder to implement.

**Comment by thrashdin** [comment]
If you make shared history, that d be very cool!
