### ISSUE TITLE
Quality of life improvements with text editing in REPL

### ISSUE THREAD

**Issue by uUJsd7PX** [neil-lindquist/SLIMA#22]
A couple of inconveniences with text editing in REPL mode:
1. Possible to move before CL-USER>when writing command. Pressing Home for example moves not to the start of the command. Would be nice if cursor didn't move beyond the start of what user writes.
2. Selection inside command line (line with CL-USER>) is invisible, but it is visible for results of the command. Should be visible in both cases, since it is functional anyway.

**Comment by neil-lindquist** [comment]
That's interesting that the selection is invisible, since I've never noticed the selection being invisible, even when testing things involving the selection. What packages do you have installed? Do you have anything in your Atom configuration file?

**Comment by neil-lindquist** [comment]
I just tried my installation of SLIMA, and selections are working correctly.

**Comment by itmuckel** [comment]
@uUJsd7PX Maybe it has also something to do with your syntax theme? I couldn't reproduce the issue.

**Comment by uUJsd7PX** [comment]
On closer inspection, it's even a bit weirder than I thought. 
Here is just cursos on command line:
![repl01](https://user-images.githubusercontent.com/858032/62761041-15ba9480-ba75-11e9-81a2-0d8f76ecab8d.PNG)
Here is with the command selected:
![repl02](https://user-images.githubusercontent.com/858032/62761132-59150300-ba75-11e9-901e-d71e6393fd6b.png)
And to compare, here is the result of other command with cursor in there:
![repl03](https://user-images.githubusercontent.com/858032/62761159-69c57900-ba75-11e9-96d8-17bf8101b3c6.PNG)
And with some result text selected:
![repl04](https://user-images.githubusercontent.com/858032/62761164-721db400-ba75-11e9-9865-d94fffdb4ddf.PNG)


My list of non-core packages:
language-lisp 0.2.0
lisp-paredit 0.6.0
slima 2.2.0
parinfer 1.23.0 (disabled)

config.cson contents:
"*":
  core:
    disabledPackages: [
      "parinfer"
    ]
    telemetryConsent: "limited"
    uriHandlerRegistration: "always"
  editor:
    fontSize: 16
    showIndentGuide: true
    softWrapAtPreferredLineLength: true
    zoomFontWhenCtrlScrolling: false
  "exception-reporting":
    userId: <id>
  "lisp-paredit":
    strict: false
  slima:
    autoStart: true
    lispName: <path to sbcl.exe>
    slimePath: <path to slime-2.24>
  welcome:
    showOnStartup: false

**Comment by uUJsd7PX** [comment]
So I "fixed" the highlight issue. It is caused by exactly the combination of Atom's default One Dark UI theme and default One Dark syntax theme. Changing any one of those or both, makes the selection visible. So only cursor thing is related to slime then.

**Comment by neil-lindquist** [comment]
Ok.  I'll probably try to take a quick look at the syntax for the repl to see if I can adjust it to behave correctly. I'd rather not exclude the use of one of the default themes. I might have hardcover a color, or misused a predefined color.

I've gotten the improvement for the home key written, so it's ready for the next release.

**Comment by neil-lindquist** [comment]
I had a chance to look at this, and the selection issue occurs because the one-dark theme (and the one-light theme) uses the same color for the selection and the highlight. So, I'm just going to remove the highlighting of the prompt line.
