### ISSUE TITLE
Make debugger text copy-able

### ISSUE THREAD

**Issue by itmuckel** [neil-lindquist/SLIMA#24]
As a CL newbie I often want to copy debugger output to paste it to help communities etc.

Currently when I select text I only get the "Split Up Down Left Right, Close Pane" menu. So the only thing left to do is `Ctrl+Shift+I` and copying the text from the html inspector 🙈 .

Can you add copying debugger output? 😅

**Comment by neil-lindquist** [comment]
I've added this to the next release. It'll copy the error message, the restarts, and the stack trace.
