### ISSUE TITLE
Print swank output to repl?

### ISSUE THREAD

**Issue by itmuckel** [neil-lindquist/SLIMA#26]
A few days ago I was going mad, because `format` wouldn't work. I put format statements everywhere in my program, but couldn't see the output.

Then I switched to Sly/Slime and there I could see the output. That's when I noticed the option `Show the swank messages in the JavaScript Console` in Slima's settings.

Is it possible to print the swank messages in the repl like Sly and Slime do? It would be nice, if I didn't have to open the JS console in order to see my format output. 🙈

**Comment by neil-lindquist** [comment]
As in `(format t "Hello World~%")` doesn't print to the REPL, but in the JS console?  It should be printing to the Slima repl.
What's your Atom version, OS, Lisp implementation, ect?

**Comment by itmuckel** [comment]
`FORMAT` writes to the REPL, that's fine.

Install the dist from [here](https://borodust.org/projects/trivial-gamekit/) and compile this in Atom:

```lisp
(ql:quickload :trivial-gamekit) 

(gamekit:defgame example () ())
(defmethod gamekit:draw ((this example))
  (format t "~s~%" "debug")
  (gamekit:draw-text "Hello, Gamedev!" (gamekit:vec2 240.0 240.0)))

(gamekit:start 'example)
```

From the sbcl repl in my terminal and also in emacs + slime/sly I get the `debug` output. In Atom + Slima the output somehow doesn't get fed back to the repl.

I'm not sure about the internals of gamekit, but maybe it executes `draw` on a different thread?

I don't think the environment is of importance here, but it's Windows 10, SBCL 1.4.14, Atom 1.40.0.

**Comment by neil-lindquist** [comment]
Ok, that makes sense.  It looks like the way `*standard-out*` is changed for the REPL doesn't play well with the thread created by gamekit.  This looks like it might be an issue with the underlying swank client.  Are you using the slime-repl contrib when you try the example in emacs+slime?

If you want a temporary solution, using `#.*standard-output*` as the stream might work, ie `(format #.*standard-output* "~s~%" "debug")`, as per https://lispcookbook.github.io/cl-cookbook/process.html

**Comment by itmuckel** [comment]
Okay, with `#.*standard-output*` I get:
```
; in: DEFMETHOD CL-BODGE.APPKIT:DRAW (MEX)
;     (FORMAT #<SWANK/GRAY::SLIME-OUTPUT-STREAM {100314E433}> "~s~%" "debug")
; ==>
;   #<SWANK/GRAY::SLIME-OUTPUT-STREAM {100314E433}>
; 
; caught ERROR:
;   don't know how to dump #<SWANK/GRAY::SLIME-OUTPUT-STREAM {100314E433}> (default MAKE-LOAD-FORM method called).
```

I didn't use `slime-repl contrib` in emacs, not in slime and not in sly.

**Comment by neil-lindquist** [comment]
I've figured out the issue. Basically, SLIMA wasn't informing the swank server that it's (pretending to be) emacs.  So, the global redirect wasn't being configured to redirect all of the output.

I've gotten a fix written on master, [if you want to try it out](https://github.com/neil-lindquist/SLIMA/wiki/Using-Development-Versions-of-SLIMA).
