### ISSUE TITLE
Interactive Restarts in Debugger

### ISSUE THREAD

**Issue by bayerf42** [neil-lindquist/SLIMA#27]
Selecting an interactive restart in the debugger (e.g. USE-VALUE or RETURN-VALUE) prompts for the value in the REPL pane, which is hidden behind the debugger, so it looks like nothing happened. Either the REPL pane should be placed in the foreground or a pop-up prompt should be displayed.

**Comment by neil-lindquist** [comment]
The suggested behavior would probably be good for any time input is requested from standard in (which means this should be easy).
