### ISSUE TITLE
Inspecting code property

### ISSUE THREAD

**Issue by bayerf42** [neil-lindquist/SLIMA#28]
When inspecting a function object, inspecting its CODE property shows several internal components, among those a disassembly listing. But this listing is not correctly line-wrapped, but is a single long string, which makes the listing totally unreadable.

**Comment by neil-lindquist** [comment]
It looks like the disassembly string doesn't follow the same conventions as the rest of the inspector strings, so the current work around doesn't protect the newlines from the HTML parser.  I should be able to fix this with CSS.
