### ISSUE TITLE
Code evaluation

### ISSUE THREAD

**Issue by mmontone** [neil-lindquist/SLIMA#35]
In SLIME we can open a file, position the cursor at the end of some expression, and evaluate it; the result showing up in status bar or the REPL (could also be in a new panel, like macroexpansion does at the moment), depending on whether slime-eval-last-expression or slime-eval-last-expression-in-repl was used.

Some version of that feature would be a cool to have, if it is not there already (I haven't found it.)

**Comment by neil-lindquist** [comment]
To make sure I'm understanding this correctly, if we have the following with `|` as the cursor,
```
(bar (foo 3)|)
```
the command would evaluate `(foo 3)`?

**Comment by mmontone** [comment]
Yes.

**Comment by neil-lindquist** [comment]
Ok, that shouldn't be to hard to implement.  Somewhere between evaluating a top level form and evaluating REPL input.

**Comment by mmontone** [comment]
Great! Should be aware of current package. I guess you may have all the pieces in places already, I see it may be similar to macro expansion.

**Comment by neil-lindquist** [comment]
I've implemented this and pushed it to master.  I set the default keystroke to <kbd>Alt</kbd>-<kbd>e</kbd> and <kbd>Ctrl</kbd>-<kbd>Cmd</kbd>-<kbd>e</kbd> to be similar to compile function/compile file.

If you want to try it and give any feedback, you can follow the instructions at https://github.com/neil-lindquist/SLIMA/wiki/Using-Development-Versions-of-SLIMA

**Comment by mmontone** [comment]
Wow! Thanks! Cheers

**Comment by mmontone** [comment]
Just tried the feature. Works perfectly. :smile:
