### ISSUE TITLE
Cannot inspect "big" vectors

### ISSUE THREAD

**Issue by mmontone** [neil-lindquist/SLIMA#37]
To reproduce, evaluate this in REPL:

```(coerce (loop repeat 500 collect 'foo) 'vector)```

Then try to inspect the presentation. In my case, the inspector doesn't show up.

**Comment by neil-lindquist** [comment]
I've reimplemented the code to load the inspection content from Swank, so it can load the entire inspection.  Its working just fine for your example, even increased to 10,000 elements.

**Comment by neil-lindquist** [comment]
This issue is now fixed in the release version.
