### ISSUE TITLE
Unable to connect with Roswell

### ISSUE THREAD

**Issue by phoe** [neil-lindquist/SLIMA#38]
Hey! Thanks for your work on slima.

My SBCL and swank are installed via Roswell and I am trying to run slima using these. I am, however, getting an error when trying to start Slime.

This command to launch SBCL works in the original emacs slime and from terminal.

![Zrzut ekranu z 2020-05-19 18-39-01](https://user-images.githubusercontent.com/15045546/82353741-1c146e80-9a00-11ea-8de6-c95c776bb04b.png)

![Zrzut ekranu z 2020-05-19 18-38-03](https://user-images.githubusercontent.com/15045546/82353614-fab38280-99ff-11ea-8a16-5f94f0619771.png)

**Comment by neil-lindquist** [comment]
The `Lisp Process` field only takes the name of the executable.  So, it should work if you just enter `ros` in that field, and SLIMA knows to pass the `run` argument (plus `-Q` is a default of Roswell).
If you need the `dynamic-space-size`, you'll need to use the `Custom Swank Command` found in the advanced options.  However, you will need to manually ensure that Swank's `start-swank.lisp` file (or equivalent) is loaded and that the port SLIMA is configured to matches the port in that file.

I'll improve the description in the settings.
