### ISSUE TITLE
Disconnecting from sbcl server kills sbcl

### ISSUE THREAD

**Issue by ashar9** [neil-lindquist/SLIMA#39]
[Enter steps to reproduce:]

1. Start independent sbcl repl with swank (from outside Atom)
2. In Atom: Connect to sbcl (OK).
3. Atom Lisp code REPL runs OK
4. Disconnect from Atom using Menu Packages - SLIMA - Lisp Processes - Disconnect

Result:
Kills sbcl (terminates screen if sbcl is running in a gnu screen)
 

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.4
**Thrown From**: [slima](https://github.com/neil-lindquist/slima) package 2.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'statusView' of undefined

```
At /Users/xa/.atom/packages/slima/lib/slima.coffee:170

TypeError: Cannot read property 'statusView' of undefined
    at /packages/slima/lib/slima.coffee:170:12)
    at /packages/slima/node_modules/swank-client/lib/client.js:78:22)
    at Socket.emit (events.js:199:15)
    at endReadableNT (_stream_readable.js:1141:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

### Commands

```
     -0:35.3.0 slime:connect (input.hidden-input)
  2x -0:31.1.0 slime:compile-function (input.hidden-input)
     -0:19.5.0 slime:disconnect (input.hidden-input)
```

### Non-Core Packages

```
atom-slime 2.8.0 
language-lisp 0.2.0 
lisp-paredit 0.7.0 
slima 2.5.0 
```

**Comment by neil-lindquist** [comment]
Looking at it, the current command should be renamed `quit` and a new command needs to be written to disconnect correctly.

As a side note, having SLIMA and Atom-Slime installed together causes occasional problems, so you probably should uninstall Atom-Slime.

**Comment by ashar9** [comment]
Thank you for the update. I had atom-slime disabled, but I will uninstall it as per your advice.

I use vim+slimv, but was setting up atom/slima for a colleague who is not a vi/emacs fan.

The current slima:eval-expression in rc.1 does not work. It just evals the lisp atom (not the enclosed form), and hence misnomer (lisp expression is a form like (* 2 3) etc). In the code below I have split it up into eval-expression and eval-atom, and changed the swank code so that eval-atom is more like describe symbol and gives its value and type and if bound or not. The current eval-expression evals the lisp atom as a variable (and gives error, even if the symbol is a defined function or macro).

The following changes were made and seem to work:

1. slima/keymaps/slima.cson 

> 'atom-workspace atom-text-editor':
>   'f8': 'slime:eval-expression'
>   'f7': 'slime:eval-atom'

2.  slima/lib/slima-editor.coffee

Line 24
    @subs.add atom.commands.add @editorElement, 'slime:eval-atom': =>
      @compileAtom()

Change the first line in compileSexp

    #sexp = @getCurrentSexp(false)
    sexp = @getCurrentSexp()  #evaluate form. zx Ashar

Added function compileAtom

 compileAtom: ->
    #  the atom that ends at the cursor
    sexp = @getCurrentSexp(false)

    if sexp and @swank.connected
      p_start = utils.convertIndexToPoint(sexp.range[0], @editor)
      p_end = utils.convertIndexToPoint(sexp.range[1], @editor)

      # Trigger the highlight effect
      range = Range(p_start, p_end)
      utils.highlightRange(range, @editor, delay=350)

      # Find file's package
      pkg = slime.getEditorPackage(@editor, p_start)

      # Trigger a compilation
      @swank.eval sexp.sexp, @pkg

      # Trigger the highlight effect
      range = Range(p_start, p_end)
      utils.highlightRange(range, @editor, delay=150)

3. Modified swank.lisp

(defun eval-region (string)
  "Evaluate STRING.
Return the results of the last form (OR ATOM) as a list and as secondary value the
last form."
  (with-input-from-string (stream string)
    (let (- values)
      (loop
       (let ((form (read stream nil stream)))
         (when (eq form stream)
           (finish-output)
           (return (values values -)))
         (setq - form)
         (if (atom form) ;zx ashar
             (if (symbolp form)
                 (let* ((p (symbol-package form))
                        (svar (intern   (string-upcase form) p )))
                    (if (not (or (boundp svar) (fboundp svar)))
                       (setq values (list (format nil "~A is an Unbound symbol~%" string)))
                       (let ((output (describe-to-string form)))
                         (setq values (list output))
                         )))
                 )
             (setq values (multiple-value-list (eval form))))
         (finish-output))))))

Swank eval-region does not seem to interfere with the vim+slimv eval form because it is called with form and not lisp atom. For atoms slimv uses inspect or describe-symbol. But if it is a problem, then I can make  separate copies of call graph functions: eval-region, repl-eval, and listener-eval and these can be submitted as lisp slime/contrib file, or can be compiled directly by Atom Editor with the swank server by passing source string at the time of Connect to swank.

**Comment by ashar9** [comment]
The following code changes work for Disconnect.
In  slima/node_modules/swank-client/lib/client.js after line 83

Client.prototype.xdisconnect = function() {
    var sc = this; // Because the 'this' operator changes scope
    if (sc.connected == true) {
        sc.socket.destroy()
        sc.connected = false
    }
}


And in lib/slima.coffee:    change quit() to xdisconnect()

@swank.xdisconnect()

**Comment by neil-lindquist** [comment]
That's basically the code I wrote for disconnect, but I was having some issues with reconnecting to the server after disconnecting so haven't gotten it committed yet.

With regard to eval-expression, its current behavior is to evaluate the expression preceding the cursor, counting symbols as expressions.  In the issue requesting the functionality (#35), it was described as such; although, I probably should have kept the name closer to SLIME's `slime-eval-last-expression`.
Adding a command to inspect a symbol in the source could would be a good functionality to add though.

**Comment by neil-lindquist** [comment]
I've gotten the disconnect/quit issue fixed and tested.

To address your other comments, I've renamed `slime:eval-expression` to `slime:eval-last-expression` to better match Emacs, and added two commands.
* `slime:eval-function` to evaluation the function call the cursor is in
* `slime:inspect` which can inspect symbols (and other expressions)

**Comment by neil-lindquist** [comment]
These improvements are now released.
