### ISSUE TITLE
Port is not used

### ISSUE THREAD

**Issue by phoe** [neil-lindquist/SLIMA#40]
I have set the port to be 4006 in the slima settings, but the emitted lisp command still lists `:port 4005`.

```lisp
;; $ cat /tmp/swank-starter.lisp.1589987016219.7517
(load "/home/phoe/.roswell/lisp/quicklisp/dists/quicklisp/software/slime-v2.24/swank-loader.lisp"
      :verbose t)
(funcall (read-from-string "swank-loader:init")
         :from-emacs t)
(funcall (read-from-string "swank:create-server") 
         :port 4005 :dont-close nil)
```

(Formatting added up there for clarity.)

![Zrzut ekranu z 2020-05-20 17-04-49](https://user-images.githubusercontent.com/15045546/82462613-167c5e80-9abc-11ea-9559-65cc83189443.png)

**Comment by neil-lindquist** [comment]
Apparently, I forgot to access the Port setting when creating the starter file.  I just fixed it in the master branch.
Thanks for bringing this to my attention.

**Comment by neil-lindquist** [comment]
This issue is now fixed in the release version.

**Comment by phoe** [comment]
Thanks!
