### ISSUE TITLE
Missing node_modules directory in the current download May 24, 2020

### ISSUE THREAD

**Issue by ashar9** [neil-lindquist/SLIMA#41]
Missing node_modules directory

Gives 'missing swank-client' or missing paredit.js etc and prevents the slima package to load.

Copying this directory from  older version solves the issue.

**Comment by neil-lindquist** [comment]
Does this happen when Atom installs the package, or when you get the repository source code?

If you're just downloading the repository source, you'll need to use Atom's `apm` utility to install the dependencies.  There are [instructions for installing a development version in the SLIMA documentation](https://github.com/neil-lindquist/SLIMA/wiki/Using-Development-Versions-of-SLIMA).

**Comment by ashar9** [comment]
I got the repository source code. The same overwrite method worked last week. Maybe the dependencies have changed in the new code.
