### ISSUE TITLE
swank connection failure when .sbclrc is customized

### ISSUE THREAD

**Issue by OoglesMcGoogles** [neil-lindquist/SLIMA#46]
I have a line in my .sbclrc to load a file at startup automatically. This works fine when I run SBCL normally through a command line, but when I try to start up SLIMA, I get an error message ("Couldn't connect to Lisp! Did you start a Lisp swank server?"). When I block out the load line in my .sbclrc, SLIMA connects successfully.

**Comment by neil-lindquist** [comment]
My first suggestion would be to try increasing the number of connection attempts in SLIMA's advanced settings.  Loading the extra file might increase the startup time to the point where SLIMA gives up before SBCL is ready.

My second suggestion would be to enable "show the swank messages in the Javascript console" in SLIMA's advanced setting.  Then open the command palette (ctrl-shift-p) and searching for "Toggle dev tools".  SBCL's stdout will be shown in that console, as well as notes from SLIMA and other packages.

**Comment by OoglesMcGoogles** [comment]
Thanks for the help! I tried increasing the number of connection attempts up to 50, and there was no change (the file isn't that big). When I start SLIMA, two lines are printed in the console: The first is "Started a swank server," (swank-starter.coffee, console.log at 52) and the second is the SBCL stdout (swank-starter.coffee, console.log at 87). That's all the output I get. Any ideas?

**Comment by neil-lindquist** [comment]
Well that eliminates the ideas I had for possible causes (slow start up time and SBCL erroring).
I've got a few ideas of questions/tests that might give some insight.

1) What version of swank/slime are you using?
2) What other Atom packages do you have installed?
2) You can try commenting out more and more of the file until SLIMA can connect (or start with an empty file and add things incrementally until it stops working).  There might be something in the file that breaks the swank server.
3) You can manually start a swank server by loading the `start-swank.lisp` file in your slime directory.  Then you should be able to connect with SLIMA's `connect` command (assuming SLIMA's address and port settings are default).  SLIMA might be starting Swank incorrectly.

**Comment by OoglesMcGoogles** [comment]
Got it--The offending line in the file was a y-or-n-p conditional. Somewhere in either swank itself or in SLIMA's swank-starter.coffee (where my guess would be check_path), having a read function wait for user input throws off the connection process. I would test it in Emacs if your excellent software didn't keep me from ever having to configure and learn Emacs.

Removing the line is a perfectly serviceable workaround for me, so thanks again for your help in diagnosing this and for your work in bringing Lisp to Atom.

**Comment by neil-lindquist** [comment]
Good to hear that you found the issue.
