### ISSUE TITLE
automatically connection to slima

### ISSUE THREAD

**Issue by nevzatseferoglu** [neil-lindquist/SLIMA#47]
Is there any way of automatically connecting to ```SLIMA``` as I open lisp file ?

**Comment by neil-lindquist** [comment]
There is a setting to automatically start SLIMA whenever Atom starts.  But there isn't a way to start just when you open lisp files.

**Comment by nevzatseferoglu** [comment]
What is that setting ?

**Comment by neil-lindquist** [comment]
It you open SLIMA'S settings, it should be the top one "Start Lisp when Atom opens".
