### ISSUE TITLE
Hope this stays active

### ISSUE THREAD

**Issue by josharmenta** [neil-lindquist/SLIMA#54]
Pulsar is really starting to come together nicely and I've now migrated from Atom to Pulsar for both day job and personal projects. This is a great tool and I hope it stays around! It works perfectly on Pulsar.

**Comment by neil-lindquist** [comment]
I've been meaning to test SLIMA on Pulsar, but hadn't yet made the time.  So, that's great to hear that it's working.
I'm hoping to keep supporting it for Pulsar, so feel free to open issues or pull requests if problems come up.

Out of curiosity, have you tried lisp-paredit or parinfer?
