### ISSUE TITLE
Unable to inspect hashmap

### ISSUE THREAD

**Issue by mark-gerarts** [neil-lindquist/SLIMA#55]
First off, I echo the sentiment of #54 and hope this extension lives on. It has been a great experience to use it so far, and works fine on Pulsar.

I have an issue when I want to inspect a hashmap in the following way:

- Evaluate an expression that yields a hashmap (serapeum style):

```lisp
(dict :x 1 :y (dict :z 2)) ; Use "Slime: Eval function" here
```

- The REPL prints something like the following:

```
#<HASH-TABLE :TEST EQUAL :COUNT 2 {1001F829B3}>
```

- Say my cursor is somewhere inside the symbol `:TEST` when I use inspect (`ctrl-i`)

```
#<HASH-TABLE :TEST EQUAL :COUNT 2 {1001F829B3}>
             ; ^ cursor is here, then C-I
```

- The inspector pops up with info about the symbol `:test`, which is not so useful:

![image](https://user-images.githubusercontent.com/11940560/211385483-076a8273-d5ab-4eea-9166-b67fbd3c84b8.png)

If I instead select/highlight the entire output and then press `ctrl-i`, I get:

```
illegal sharp macro character: #\<

  Stream: #<dynamic-extent STRING-INPUT-STREAM (unavailable) from "(quote #...">
   [Condition of type SB-INT:SIMPLE-READER-ERROR]
Restarts: 
  0: [RETRY] Retry SLIME inspection request.
  1: [*ABORT] Return to SLIME's top level.
  2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {10052E0003}>)
Stack Trace: 
  0: (SB-IMPL::SHARP-ILLEGAL #<SB-IMPL::STRING-INPUT-STREAM {7FCAB191E013}> #\< #<unused argument>)
  1: (SB-IMPL::READ-MAYBE-NOTHING #<SB-IMPL::STRING-INPUT-STREAM {7FCAB191E013}> #\#)
  2: (SB-IMPL::READ-LIST #<SB-IMPL::STRING-INPUT-STREAM {7FCAB191E013}> #<unused argument>)
  3: (SB-IMPL::READ-MAYBE-NOTHING #<SB-IMPL::STRING-INPUT-STREAM {7FCAB191E013}> #\()
  4: (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SB-IMPL::STRING-INPUT-STREAM {7FCAB191E013}> T (NIL) T)
  5: (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SB-IMPL::STRING-INPUT-STREAM {7FCAB191E013}> T (NIL) NIL)
  6: (READ #<SB-IMPL::STRING-INPUT-STREAM {7FCAB191E013}> T NIL NIL)
  7: (SB-IMPL::%READ-FROM-STRING "(quote #<HASH-TABLE :TEST EQUAL :COUNT 2 {1001F829B3}>)" T NIL 0 NIL NIL)
  8: ((LAMBDA NIL :IN SWANK:INIT-INSPECTOR))
  9: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME inspection request." #<FUNCTION (LAMBDA NIL :IN SWANK:INIT-INSPECTOR) {10027D053B}>)
  10: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<FUNCTION (LAMBDA NIL :IN SWANK:INIT-INSPECTOR) {10027D051B}>)
  11: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SWANK:INIT-INSPECTOR "(quote #<HASH-TABLE :TEST EQUAL :COUNT 2 {1001F829B3}>)") #<NULL-LEXENV>)
  12: (EVAL (SWANK:INIT-INSPECTOR "(quote #<HASH-TABLE :TEST EQUAL :COUNT 2 {1001F829B3}>)"))
  13: (SWANK:EVAL-FOR-EMACS (SWANK:INIT-INSPECTOR "(quote #<HASH-TABLE :TEST EQUAL :COUNT 2 {1001F829B3}>)") "CL-USER" 279)
  14: (SWANK::PROCESS-REQUESTS NIL)
  15: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
  16: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
  17: (SWANK/SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<FUNCTION (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {1001B2802B}>)
  18: ((FLET SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/home/mark/.emacs.d/.local/straight/repos/slime/swank/sbcl.lisp") #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<FUNCTION (LAMBDA NIL :IN SWANK::HANDLE-REQUE..
  19: (SWANK::CALL-WITH-BINDINGS ((*STANDARD-INPUT* . #<SWANK/GRAY::SLIME-INPUT-STREAM {1001888E83}>)) #<FUNCTION (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {1001B2804B}>)
  20: (SWANK::HANDLE-REQUESTS #<SWANK::MULTITHREADED-CONNECTION {100444A813}> NIL)
  21: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
  22: ((FLET "WITHOUT-INTERRUPTS-BODY-132" :IN SB-THREAD::RUN))
  23: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
  24: ((FLET "WITHOUT-INTERRUPTS-BODY-125" :IN SB-THREAD::RUN))
  25: (SB-THREAD::RUN)
  26: ("foreign function: call_into_lisp_")
  ```

**Comment by mark-gerarts** [comment]
These are my specs:

- OS: OpenSUSE
- SBCL 2.3.0-1.1-suse
- Pulsar  : 1.100.0-beta
- SLIME v2.27

I tried again today and noticed that the problem only occurs when I send something to the REPL from the file I'm working in, using `slime:eval-last-expression`. If I type e.g. `(dict :x 1)` in the REPL directly, I can inspect the result as expected.

**Comment by josharmenta** [comment]
@mark-gerarts This was reported to me by someone on my team as well, seems as it is repeatable.

**Comment by neil-lindquist** [comment]
I was able to reproduce the issue when eval-ing from a file.
Unfortunately, switching to Pulsar broke my development workflow, so I need to figure out how to set that up again.

**Comment by neil-lindquist** [comment]
I think I've fixed this.
Feel free to try the dev version; the process should be [the same as Atom](https://github.com/neil-lindquist/SLIMA/wiki/Using-Development-Versions-of-SLIMA).  (You won't need a dev version of `swank-client`).
Otherwise, I'll try to get a new release soon.

**Comment by neil-lindquist** [comment]
I just made a new release with the fix.  (The Pulsar website doesn't yet show it, but you should be able to update the package.)
Sorry for the delay, I had to wait for some Pulsar bugfixes and got busy with grad school.
