### ISSUE TITLE
slime 2.28 hangs

### ISSUE THREAD

**Issue by hemml** [neil-lindquist/SLIMA#58]
Hi!

After updating slime to 2.28, every command hangs after finishing. Ctrl-C in REPL cannot interrupt it and only duplicates output of the command:

```
CL-USER> (print "asdfasfasdf")

"asdfasfasdf" ;; Ctrl-C pressed 3 times
"asdfasfasdf" 
"asdfasfasdf" 
"asdfasfasdf" 
```
The same happens not only when connecting locally, but also when connecting to a remote swank server, where slime 2.28 installed, even if the local slime version is 2.26.

**Comment by hemml** [comment]
It is a swank-client issue, I have made a pull-request to fix it: https://github.com/neil-lindquist/swank-client/pull/2

**Comment by neil-lindquist** [comment]
I got locked out of my NPM account, so I have to resolve that before I can release the new swank-client.  But, I'm hoping to get this fixed within the next week.
