### ISSUE TITLE
slima error on debian 12

### ISSUE THREAD

**Issue by faywong** [neil-lindquist/SLIMA#61]
```shell
Uncaught TypeError: Cannot read property 'activate' of undefined

/home/faywong/.pulsar/packages/slima/lib/slima-repl-view.coffee:589
Hide Stack Trace
TypeError: Cannot read property 'activate' of undefined
    at /home/faywong/.pulsar/packages/slima/lib/slima-repl-view.coffee:589:24
```

**Comment by neil-lindquist** [comment]
Can you share what steps lead to this error?  From the line number, I'm guessing something with the debugger, but I'm not getting any errors when I use the debugger.

It might also be helpful if you share your Lisp implementation and version and Pulsar version.

**Comment by faywong** [comment]
I wll attach more info when it re-produced. I switch to vim-slime plugin right now and it works well.
